In [1]:
import numpy as np

In [2]:
T = 1.0
F = 0.0



In [3]:
def get_AND_data():
    X = [
        [F, F],
        [F, T],
        [T, F],
        [T, T]
    ]

    Y = [
        [F],
        [F],
        [F],
        [T]
    ]

    return np.array(X), np.array(Y)

X, Y = get_AND_data()


In [4]:
class MyPerceptron:
    def __init__(self, learning_rate=0.1, n_iterations=1000):
        self.lr = learning_rate
        self.epochs = n_iterations
        self.weights = None
        self.bias = None

    def step_activ_func(self, activation):
        if activation >= 0:
            return 1
        else:
            return 0

    def fit(self, X, Y):
        self.weights = np.zeros(X.shape[1])
        self.bias = 0

        for epoch in range(self.epochs):
            for i in range(X.shape[0]):
                linear_output = np.dot(self.weights, X[i]) + self.bias
                y_pred = self.step_activ_func(linear_output)

                error = Y[i][0] - y_pred

                self.weights += self.lr * error * X[i]
                self.bias += self.lr * error

    def predict(self, X):
        y_pred = []
        for i in range(X.shape[0]):
            linear_output = np.dot(self.weights, X[i]) + self.bias
            y_pred.append(self.step_activ_func(linear_output))
        return np.array(y_pred)

In [5]:
clf = MyPerceptron()
clf.fit(X, Y)

X_test = np.array([
    [F, F],
    [F, T],
    [T, F],
    [T, T]
])

Y_predicted = clf.predict(X_test)
print("Predicted Output:")
print(Y_predicted)


Predicted Output:
[0 0 0 1]


In [6]:
def get_OR_data():
    X = [
        [F, F],
        [F, T],
        [T, F],
        [T, T]
    ]

    Y = [
        [F],
        [T],
        [T],
        [T]
    ]

    return np.array(X), np.array(Y)

In [7]:
def get_XOR_data():
    X = [
        [F, F],
        [F, T],
        [T, F],
        [T, T]
    ]

    Y = [
        [F],
        [T],
        [T],
        [F]
    ]

    return np.array(X), np.array(Y)


In [8]:
# OR Gate
X_or, Y_or = get_OR_data()

clf_or = MyPerceptron()
clf_or.fit(X_or, Y_or)

Y_pred_or = clf_or.predict(X_or)

print("OR Gate Predicted Output:")
print(Y_pred_or)

OR Gate Predicted Output:
[0 1 1 1]


In [9]:
# XOR Gate
X_xor, Y_xor = get_XOR_data()

clf_xor = MyPerceptron()
clf_xor.fit(X_xor, Y_xor)

Y_pred_xor = clf_xor.predict(X_xor)

print("XOR Gate Predicted Output:")
print
(Y_pred_xor)


XOR Gate Predicted Output:


array([1, 1, 0, 0])